inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

AsciiComments:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false
