default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV["DB_USER"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  port: <%= ENV["DB_PORT"] || 3306 %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_api_development

test:
  <<: *default
  database: rails_api_test

production:
  <<: *default
  database: rails_api_production
